### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by akash23** [itsananderson/itsananderson.github.io#2]
Hi,
As per your suggestion the following link was broken. Request to fix it.
PS: your article is really helpful.

http://willi.am/blog/2014/07/09/azure-blob-storage-and-node-all-together/blog/2014/07/08/azure-blob-storage-and-node-blob-metadata/

**Comment by akash23** [comment]
I guess the link given in your All together page (http://willi.am/blog/2014/07/09/azure-blob-storage-and-node-all-together/) is improper otherwise it's working fine.

**Comment by itsananderson** [comment]
Fixed. Thanks for reporting
